// <auto-generated />
namespace QLTeam.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CapBac_Active : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CapBac_Active));
        
        string IMigrationMetadata.Id
        {
            get { return "202110230638396_CapBac_Active"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
